language: objective-c
osx_image: xcode8.2
xcode_project: EMS.xcodeproj
xcode_scheme: EMS
xcode_sdk: iphonesimulator10.0
before_install:
- gem install xcpretty
script:
- xcodebuild -scheme EMS -project EMS.xcodeproj -configuration 'Debug' -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0’ clean build test
