language: objective-c
osx_image: xcode8.2
xcode_workspace: EMS.xcworkspace
xcode_scheme: EMSTests
xcode_sdk: iphonesimulator10.2
before_install:
- gem install xcpretty
script:
- xcodebuild -scheme EMS -project EMS.xcodeproj -configuration 'Debug' -destination "platform=iOS Simulator,name=iPhone 7,OS=10.2" clean build test
